pipeline {
  agent any

  parameters {
    choice(name: 'DEPLOY_ENV', choices: ['blue', 'green'], description: 'Blue or Green')
    choice(name: 'ENV', choices: ['dev', 'qa', 'prod'], description: 'Environment')
  }

  environment {
    IMAGE = "vani5652/blue-green-demo:${DEPLOY_ENV}-${ENV}-${BUILD_NUMBER}"
    GIT_REPO = "https://github.com/vani544/blue-green-vani-pipeline.git"
    ARGO_APP = "blue-green-app"
  }

  stages {

    stage('Checkout') {
      steps {
        git branch: 'main', url: "${GIT_REPO}"
      }
    }

    stage('Build & Push Image') {
      steps {
        sh """
          docker build -t ${IMAGE} .
          docker push ${IMAGE}
        """
      }
    }

    stage('Update K8S files in Git') {
      steps {
        sh """
          sed -i "s|IMAGE_TAG|${IMAGE}|g" k8s/deployment.yaml
          sed -i "s|DEPLOY_ENV|${DEPLOY_ENV}|g" k8s/deployment.yaml
          sed -i "s|DEPLOY_ENV|${DEPLOY_ENV}|g" k8s/service.yaml
        """
      }
    }

    stage('Commit & Push to Git') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'github-pat',
          usernameVariable: 'GIT_USER',
          passwordVariable: 'GIT_TOKEN'
        )]) {
          sh """
            git config user.email "vani.vanisri28@gmail.com"
            git config user.name "vani544"

            git remote set-url origin https://${GIT_USER}:${GIT_TOKEN}@github.com/vani544/blue-green-vani-pipeline.git

            git add k8s/
            git commit -m "Deploy ${DEPLOY_ENV} to ${ENV}" || echo "No changes to commit"
            git push origin main
          """
        }
      }
    }

  } 
} 
