pipeline {
  agent any

  parameters {
    choice(name: 'DEPLOY_ENV', choices: ['blue', 'green'], description: 'Blue or Green')
    choice(name: 'ENV', choices: ['dev', 'qa', 'prod'], description: 'Environment')
  }

  environment {
    IMAGE = "vani5652/blue-green-demo:${DEPLOY_ENV}-${ENV}-${BUILD_NUMBER}"
    GIT_REPO = "https://github.com/vani544/blue-green-app.git"
    ARGO_APP = "blue-green-app"
  }

  stages {

    stage('Checkout') {
      steps {
        git branch: 'main', url: "${GIT_REPO}"
      }
    }

    stage('Build & Push Image') {
      steps {
        sh """
        docker build -t ${IMAGE} .
        docker push ${IMAGE}
        """
      }
    }

    stage('Update Manifests') {
      steps {
        sh """
        sed -i "s|IMAGE_PLACEHOLDER|${IMAGE}|g" k8s/deployment.yaml
        sed -i "s|DEPLOY_ENV|${DEPLOY_ENV}|g" k8s/deployment.yaml
        sed -i "s|DEPLOY_ENV|${DEPLOY_ENV}|g" k8s/service.yaml
        """
      }
    }

    stage('Commit & Push to Git') {
      steps {
        sh """
        git config user.email "vani.vanisri28@gmail.com"
        git config user.name "vani544"
        git add k8s/
        git commit -m "Deploy ${DEPLOY_ENV} to ${ENV}"
        git push origin main
        """
      }
    }

    stage('Trigger Argo CD Sync') {
      steps {
        sh """
        argocd app sync ${ARGO_APP}
        argocd app wait ${ARGO_APP} --health
        """
      }
    }
  }
}
